'use client';

import React from 'react';
import Link from 'next/link';
import { Sparkle } from '@/components/ui/Badge';

export default function TermsPage() {
  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'var(--surface)',
        padding: '32px',
      }}
    >
      <div
        style={{
          width: '100%',
          maxWidth: '720px',
          animation: 'fadeIn var(--transition-smooth) ease-out forwards',
        }}
      >
        <div style={{ textAlign: 'center', marginBottom: '40px' }}>
          <Link href="/" style={{ textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
            <Sparkle color="var(--magenta)" size={28} />
            <span style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-2xl)', textTransform: 'uppercase', color: 'var(--ink)' }}>ADWEN</span>
          </Link>
        </div>

        <div
          style={{
            background: 'var(--surface-2)',
            borderRadius: 'var(--radius-card)',
            padding: 'var(--space-8)',
            boxShadow: 'var(--shadow-elevated)',
          }}
        >
          <h1 style={{ fontSize: 'var(--text-xl)', fontWeight: 800, fontFamily: 'var(--font-display)', marginBottom: '24px' }}>
            Terms and Conditions
          </h1>

          <div style={{ fontSize: 'var(--text-sm)', color: 'var(--muted)', lineHeight: 1.8, display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <p><strong style={{ color: 'var(--ink)' }}>Effective Date:</strong> June 2025</p>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>1. Acceptance of Terms</h2>
              <p>By creating an account and using Adwen, you agree to these Terms and Conditions. If you do not agree, please do not use the platform.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>2. What Adwen Is</h2>
              <p>Adwen is an AI-powered adaptive learning platform designed for university students. It generates personalised quiz questions, tracks your learning behaviour, and provides intelligent study insights to help you prepare for exams.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>3. Your Account</h2>
              <p>You are responsible for maintaining the confidentiality of your login credentials. You must provide accurate information when creating your account. We reserve the right to suspend accounts that violate these terms.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>4. Acceptable Use</h2>
              <p>You agree not to misuse the platform, including but not limited to: attempting to reverse-engineer the AI system, sharing your account with others, or using the platform for any unlawful purpose.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>5. AI-Generated Content</h2>
              <p>Quiz questions and insights are generated by artificial intelligence. While we strive for accuracy, Adwen does not guarantee the correctness of AI-generated content. It is a study aid, not a substitute for course materials or lecturer guidance.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>6. Intellectual Property</h2>
              <p>All content, design, and technology on Adwen are the property of the Adwen team. You may not reproduce, distribute, or create derivative works without prior written consent.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>7. Data Collection</h2>
              <p>We collect learning telemetry data (response times, accuracy, quiz patterns) to personalise your experience. For full details, see our <Link href="/privacy" style={{ color: 'var(--cobalt)', fontWeight: 600 }}>Privacy Policy</Link>.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>8. Limitation of Liability</h2>
              <p>Adwen is provided &quot;as is&quot; without warranties of any kind. We are not liable for any academic outcomes, decisions, or consequences arising from your use of the platform.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>9. Changes to These Terms</h2>
              <p>We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance of the new terms.</p>
            </section>

            <section>
              <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>10. Contact</h2>
              <p>If you have questions about these terms, reach out to us at <strong style={{ color: 'var(--ink)' }}>support@adwen.study</strong>.</p>
            </section>
          </div>
        </div>

        <p style={{ textAlign: 'center', marginTop: '24px', color: 'var(--muted)', fontSize: 'var(--text-sm)' }}>
          <Link href="/signup" style={{ color: 'var(--cobalt)', fontWeight: 600 }}>
            ← Back to Sign up
          </Link>
        </p>
      </div>
    </div>
  );
}
